### ISSUE TITLE
Log retriever capability

### ISSUE THREAD

**Issue by LittleJohnII** [wildfly-extras/sunstone#32]
A suggestion by @jmartisk 

A LogRetriever class could be implemented that would be capable of opening a continuous stream of bytes from a remote text file after being passed the location of the text file and a handler class that would consume the bytes. Declarative approach could be used to specify the handlers and remote files.

@jmartisk could you specify how you imagined this would work? Thanks!

**Comment by jmartisk** [comment]
The idea is that a ssh client will continously run `tail -f $LOG_FILE` against a log file in a remote node, so they will be transferred to the test's JVM immediately where they can be further processed, for example written to the test console output, or the test could react to an error message by stopping itself, etc. 

This will only work for nodes with ssh access configured properly. I already tested it with Azure image `eap-7-rhel-7.2` and it worked fine.

The design currently looks like this:
- You define `Retriever`s, which is an object that takes care of streaming the logs continuously from the remote node and passes it to handlers.
- A `Handler` is an object which does whatever is needed for each received log.
- One `Retriever` is bound to only one node and one file on that node. It can use multiple handlers though.

## Declarative configuration
```
node0.logging.retrievers=retriever1
node0.logging.retriever1.file=/opt/rh/eap7/root/usr/share/wildfly/standalone/log/server.log
node0.logging.retriever1.handlers=org.wildfly.extras.sunstone.logging.ConsoleEcho,some.other.Handler
```
(or you can assign LogRetriever instances to a node programatically at runtime...)

## Handler
This one would simply echo every log from the VM to the test's console log:
```java
public class ConsoleEcho implements LogHandler {

    private static final Logger logger = LoggerFactory.getLogger(ConsoleEcho.class);

    @Override
    public void handleLog(String log, Node node) {
        logger.info("[## " + node +" ##] " + log);
    }

    @Override
    public void handleError(String error, Node node) {
        logger.info("[ERROR ## " + node +" ##] " + error);
    }
}
```

Important is to note that `handleError` method doesn't refer to handling a log containing an ERROR, it refers to handling an error which occurred when reading the logs (that is, it occurred in the stderr of the `tail -f` process).

## Retriever
This is the class which contains logic for streaming the logs from the remote node and passing them to the handlers.
It contains `start()` and `finish()` methods which will be called by sunstone when the node is started/stopped. The logic for the streaming runs in a separate thread which is managed by the Retriever object.

**Comment by Ladicek** [comment]
I agree that streaming / "tailing" a remote file is very useful, but I'm not totally convinced that the "declarative" approach is the best idea. (What's the lifecycle? What if the file doesn't exist? What if the file gets deleted? What if the file gets log-rotated? What if I want to stream multiple files, e.g. a WildFly log and a dedicated GC log? How are errors handled? What are the data consistency guarantees? Is there a programmatic API also planned and if yes, what are the differences?  All that should, IMHO, be handled by the user, unless there's a convincing answer that is general enough.)

But then, this isn't really my project, so... :-)

**Comment by jmartisk** [comment]
You're definitely right that the declarative approach brings in some issues, I just thought it would be nice to be able to specify this for a node globally, so each test using the node could make use of it automatically without the test developer having to pollute the testcase's code with it.

The lifecycle would be that Sunstone starts it right after the node starts and stops it after the node stops. We'd just have to try our best to make sure we don't close it too early because that would mean possibly losing some logs.

Programmatic API would be supported too, you could even combine them together. It would offer pretty much the same functionality, you would just be able to call  `start` and `stop` when you want it. There could also be the possibility to obtain the status of the retriever in case of an error, but I'm not sure if that is very useful (if the test case finds out that the retriever had an error, what can we (programatically) do about it? mostly nothing except logging it and moving on without interrupting the test..)

If you need more files, you could just create more log retrievers (they can use the same log handler if you want to). Alternatively we could make one retriever be able to tail more files, but I don't see that as necessary. Or, see below, my proposed solution for rotating files kinda resolves this too:

### Rotating log files
About rotating log files, that's a good point I didn't think about earlier. I guess it's not easy to generally find out where the logging is currently taking place or to detect when log rotation happens.

I have an idea though. What about, instead of tailing one file via ssh, we could run a small (probably Java) process on the node (again via SSH and keeping track of its stdin/stdout), which would monitor a defined `logs` directory for any new files and tail all of them at once - and combine logs from them and send them back via its stdout? We would just have to make sure we're able to parse that stream on test's side, probably we would have to introduce some particular format in there to be able to find logs and the name of the file where the log comes from:

`#server.log#some sort of log#gc.log#full GC at 16:35:12#server.log#another log`
(obviously the delimter would be something different than `#` that we don't expect to appear in any logs)

The retriever would be configured by a directory parameter rather than a file parameter. The handler's `handleLog` method would receive a new parameter, the log file name. Based on the log file name, it could handle logs from different files in a different way, or decide to ignore some logs that don't interest us.

Obviously using some message-oriented network protocol would be more flexible for this than parsing stdin/stdout, but then we would probably need to open some more network ports and it sounds like an overkill to me.

**Comment by Ladicek** [comment]
Where I'm coming from -- remote logs are useful for more things than just copying them to local test log. E.g. important part of the test can be analysing the log for known bad patterns. This can of course be done after the test finishes (`copyFileFromNode`); in fact, it's better to do it that way because that has reasonable consistency guarantees.

But then, I'd argue that downloading remote logs at the end of the test so that they are available alongside local test log is also better than intermixing the test log with a remote log (especially when streaming the remote log becomes slow, which means that the resulting log won't actually be ordered).

I guess what I'm really asking about is: usecases?

Re log rotation -- the simplest case can be solved by using `tail -F` instead of `-f`, but I don't know if it's sufficient for all our use cases or if it's available on all platforms we care about.

**Comment by kwart** [comment]
IMO, the LogRetriever feature doesn't fit to existing modules. We should consider `sunstone-tools` or so.

The possibility of the declarative approach takes me back to the "extensions topic" (#20). If we have Node listeners/observers functionality, then the suggested LogRetriever implementation is a simple implementation of the standard interface.

**Comment by Ladicek** [comment]
Agreed that lifecycle listeners seem to be a good fit for this.

**Comment by istraka** [comment]
This is for 1.x branch which is in a maintenance mode.
